twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig','@TalesFromADevFlowbite/form/default.html.twig']
    globals:
        getDescription: '@App\Twig\FunctionExtension'


when@test:
    twig:
        strict_variables: true
